stages:
  - validate
  - connectivity

ansible-validate:
  stage: validate
  tags:
    - network

  script:
    - ansible --version
    - ansible-inventory -i inventory/hosts.yml --list
    - ansible-playbook --syntax-check playbooks/ospf.yml
    - ansible-playbook --syntax-check playbooks/mpls.yml
    - ansible-playbook --syntax-check playbooks/L3vpn/VRFs.yml
    - ansible-playbook --syntax-check playbooks/L3vpn/ce-ebgp.yml
    - ansible-playbook --syntax-check playbooks/L3vpn/pe-rr-ibgp.yml
    - ansible-playbook --syntax-check playbooks/L3vpn/mp-bgp.yml

ce1-connectivity:
  stage: connectivity
  tags:
    - network

  script:
    - ansible CE1 -i inventory/hosts.yml
        -m ansible.netcommon.cli_command
        -a 'command="show version"'