stages:
  - test

ansible-test:
  stage: test

  tags:
    - network

  script:
    - echo "=== Ansible version ==="
    - ansible --version

    - echo "=== Ansible collections ==="
    - ansible-galaxy collection list

    - echo "=== Inventory ==="
    - ansible-inventory -i inventory/hosts.yml --list