all:
  vars:
    ansible_user: idriss
    ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
    ansible_enable_password: "{{ lookup('env', 'ANSIBLE_ENABLE_PASSWORD') }}"
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_ssh_common_args: '-o KexAlgorithms=diffie-hellman-group14-sha1 -o HostKeyAlgorithms=ssh-rsa -o StrictHostKeyChecking=no'

  children:
    ce_routers:
      hosts:
        CE1:
          ansible_host: CE1.isp-network.com
        CE2:
          ansible_host: CE2.isp-network.com  
        CE3:
          ansible_host: CE3.isp-network.com
        CE4:
          ansible_host: CE4.isp-network.com

    pe_routers:
      hosts:
        PE1:
          ansible_host: PE1.isp-network.com
        PE2:
          ansible_host: PE2.isp-network.com
        PE3:
          ansible_host: PE3.isp-network.com
        PE4:
          ansible_host: PE4.isp-network.com

    route_reflectors:
      hosts:
        RR:
          ansible_host: RR.isp-network.com
    
    p_routers:
      hosts:
        P1:
          ansible_host: P1.isp-network.com

