interfaces:
  - name: Loopback0
    ip: 33.33.33.33
    mask: 255.255.255.255
    description: LOOPBACK

  - name: GigabitEthernet0/0
    ip: 10.10.2.1
    mask: 255.255.255.0
    description: LINK-TO-Client2

  - name: GigabitEthernet0/1
    ip: 10.0.1.17
    mask: 255.255.255.252
    description: LINK-TO-PE2

  - name: GigabitEthernet0/3
    ip: 10.0.3.5
    mask: 255.255.255.252
    description: LINK-TO-PE1

mgmt_interface:
  name: GigabitEthernet0/2
  ip: 192.168.122.17
  mask: 255.255.255.0
  description: MANAGEMENT

bgp_as: 300
loopback_ip: 33.33.33.33
bgp_ce_neighbors:
  - ip: 10.0.1.18
    remote_as: 65000

  - ip: 10.0.3.6
    remote_as: 65000

bgp_networks:
  - prefix: 10.10.2.0
    mask: 255.255.255.0

dhcp_pools:
  - name: LAN1
    network: 10.10.2.0/24
    excluded_end: 10
    dns_server: 192.168.122.1
    lease_days: 1
