---
interfaces:
  - name: Loopback0
    ip: 1.1.1.1
    mask: 255.255.255.255
    description: LOOPBACK

  - name: GigabitEthernet0/0
    ip: 10.0.1.2
    mask: 255.255.255.252
    description: LINK-TO-CE1
    vrf: Customer_A

  - name: GigabitEthernet0/1
    ip: 10.0.1.5
    mask: 255.255.255.252
    description: LINK-TO-RR
    ospf-cost: 100

  - name: GigabitEthernet0/3
    ip: 10.0.3.6
    mask: 255.255.255.252
    description: LINK-TO-CE3
    vrf: Customer_B

  - name: GigabitEthernet0/4
    ip: 10.0.2.1
    mask: 255.255.255.252
    description: LINK-TO-P1
    ospf-cost: 10
mgmt_interface:
  name: GigabitEthernet0/2
  ip: 192.168.122.11
  mask: 255.255.255.0
  description: MANAGEMENT

loopback_ip: 1.1.1.1
bgp_as: 65000
ospf_process_id: 110
ospf_networks:
  - prefix: 1.1.1.1
    wildcard: 0.0.0.0
    area: 0
  - prefix: 10.0.1.0
    wildcard: 0.0.0.255
    area: 0
  - prefix: 10.0.2.0
    wildcard: 0.0.0.255
    area: 0

bgp_rr_neighbors:
  - ip: 5.5.5.5
    remote_as: 65000


mpls_interfaces:
  - GigabitEthernet0/1
  - GigabitEthernet0/4

vrfs:
  - name: Customer_A
    rd: "65000:1"
    rt_export: "65000:100"
    rt_import: "65000:100"
    bgp_ce_neighbors:
      - ip: 10.0.1.1
        remote_as: 100

  - name: Customer_B
    rd: "65000:2"
    rt_export: "65000:200"
    rt_import: "65000:200"
    bgp_ce_neighbors:
      - ip: 10.0.3.5
        remote_as: 300

path_control_prefix_lists:

  - name: CE2-ROUTES
    prefix: 10.10.3.0/24

  - name: CE4-ROUTES
    prefix: 10.10.4.0/24


path_control_route_maps:

  - name: VRF-B-BACKUP
    lines:
      - "match ip address prefix-list CE4-ROUTES"
      - "set as-path prepend 65000 65000"

  - name: VRF-A-PRIMARY
    lines:
      - "match ip address prefix-list CE2-ROUTES"


path_control_neighbors:

  - vrf: Customer_A
    neighbor: 10.0.1.1
    route_map: VRF-A-PRIMARY

  - vrf: Customer_B
    neighbor: 10.0.3.5
    route_map: VRF-B-BACKUP
