---
- name: Save configuration
  hosts: all
  gather_facts: false

  tasks:
    - name: remove banner from devices
      cisco.ios.ios_config:
        lines:
          - no banner login
          - no banner exec
          - no banner incoming
        
    - name: Save configuration
      cisco.ios.ios_config: 
        save_when: always
